### ISSUE TITLE
Functionality can be implemented using CSS, no need to run expensive JS

### ISSUE THREAD

**Issue by ngyikp** [aschuhardt/Discord-Blocked-Blocker#1]
```css
div[class^="messageGroupBlocked-"], div[class*=" messageGroupBlocked-"] {
    display: none !important;
}
```
